---
- name: Install base package
  sudo: yes
  pacman:
    name: "{{ zsh_base_pkg }}"
    state: present
    update_cache: yes

- name: Install extra package
  sudo: yes
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ zsh_doc_pkg }}"
    - "{{ zsh_completations_pkg }}"
    - "{{ zsh_highlighting_pkg }}"
  when: zsh_extra_pkg is defined

- name: Check for Oh My Zsh
  stat:
    path: "{{ lookup('env','ZSH') }}/tools/uninstall.sh"
  register: oh_my_zsh_check

- name: Install Oh My Zsh
  shell: >
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  when: oh_my_zsh_check.stat.exists == False
