---
### Archlinux
- name: Install Zsh
  include: archlinux/install_zsh.yml

### Common
- name: Install Oh My Zsh
  include: common/install_oh_my_zsh.yml

- name: Configure Zsh
  include: common/configure_oh_my_zsh.yml
