---
- name: Install base package Arch Linux
  sudo: yes
  pacman:
    name: "{{ zsh_base_pkg }}"
    state: present
    update_cache: yes
  tags:
    - archlinux

- name: Install extra package Arch Linux
  sudo: yes
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ zsh_doc_pkg }}"
    - "{{ zsh_completations_pkg }}"
    - "{{ zsh_highlighting_pkg }}"
  when: zsh_extra_pkg == true
  tags:
    - archlinux
