---
- name: Set default Shell
  sudo: yes
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh

- name: Check for Oh My Zsh
  stat:
    path: "{{ lookup('env','ZSH') }}/tools/uninstall.sh"
  register: oh_my_zsh_check
  when: zsh_extra_pkg == true

- name: Install Oh My Zsh
  shell: >
    export SHELL=/bin/zsh && \
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  when: oh_my_zsh_check.stat.exists == False and zsh_extra_pkg is defined
